// Generated by `supabase gen types typescript` from supabase/migrations — do not edit.
// Regenerate: npm run db:types (local) or npx supabase gen types typescript --project-id <ref>

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      dm_conversations: {
        Row: {
          id: string;
          kind: string;
          direct_key: string;
          created_at: string;
          last_message_at: string | null;
        };
        Insert: {
          id?: string;
          kind?: string;
          direct_key?: string;
          created_at?: string;
          last_message_at?: string | null;
        };
        Update: {
          id?: string;
          kind?: string;
          direct_key?: string;
          created_at?: string;
          last_message_at?: string | null;
        };
        Relationships: [];
      };
      dm_participants: {
        Row: {
          conversation_id: string;
          user_id: string;
          joined_at: string;
          last_read_at: string;
          last_delivered_at: string;
        };
        Insert: {
          conversation_id?: string;
          user_id?: string;
          joined_at?: string;
          last_read_at?: string;
          last_delivered_at?: string;
        };
        Update: {
          conversation_id?: string;
          user_id?: string;
          joined_at?: string;
          last_read_at?: string;
          last_delivered_at?: string;
        };
        Relationships: [
          { foreignKeyName: "dm_participants_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      dm_messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          sender_device_id: string;
          content: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          sender_device_id?: string;
          content?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          sender_device_id?: string;
          content?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      e2e_devices: {
        Row: {
          user_id: string;
          device_id: string;
          device_keys: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id?: string;
          device_id?: string;
          device_keys?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          device_id?: string;
          device_keys?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      e2e_to_device: {
        Row: {
          id: number;
          recipient_id: string;
          recipient_device: string;
          sender_id: string;
          event_type: string;
          content: Json;
          created_at: string;
        };
        Insert: {
          id?: number;
          recipient_id?: string;
          recipient_device?: string;
          sender_id?: string;
          event_type?: string;
          content?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          recipient_id?: string;
          recipient_device?: string;
          sender_id?: string;
          event_type?: string;
          content?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      user_blocks: {
        Row: {
          blocker_id: string;
          blocked_id: string;
          created_at: string;
        };
        Insert: {
          blocker_id?: string;
          blocked_id?: string;
          created_at?: string;
        };
        Update: {
          blocker_id?: string;
          blocked_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      admin_audit_log: {
        Row: {
          action: string;
          admin_id: string | null;
          created_at: string;
          details: Json;
          id: string;
          summary: string;
          target_id: string | null;
          target_type: string;
        };
        Insert: {
          action: string;
          admin_id?: string | null;
          created_at?: string;
          details?: Json;
          id?: string;
          summary: string;
          target_id?: string | null;
          target_type: string;
        };
        Update: {
          action?: string;
          admin_id?: string | null;
          created_at?: string;
          details?: Json;
          id?: string;
          summary?: string;
          target_id?: string | null;
          target_type?: string;
        };
        Relationships: [
          {
            foreignKeyName: "admin_audit_log_admin_id_fkey";
            columns: ["admin_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      app_admins: {
        Row: {
          granted_at: string;
          note: string | null;
          user_id: string;
        };
        Insert: {
          granted_at?: string;
          note?: string | null;
          user_id: string;
        };
        Update: {
          granted_at?: string;
          note?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "app_admins_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      follows: {
        Row: {
          created_at: string;
          followee_id: string;
          follower_id: string;
        };
        Insert: {
          created_at?: string;
          followee_id: string;
          follower_id?: string;
        };
        Update: {
          created_at?: string;
          followee_id?: string;
          follower_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "follows_followee_id_fkey";
            columns: ["followee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "follows_follower_id_fkey";
            columns: ["follower_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          actor_id: string;
          created_at: string;
          id: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          post_id: string | null;
          read_at: string | null;
          recipient_id: string;
        };
        Insert: {
          actor_id: string;
          created_at?: string;
          id?: string;
          kind: Database["public"]["Enums"]["notification_kind"];
          post_id?: string | null;
          read_at?: string | null;
          recipient_id: string;
        };
        Update: {
          actor_id?: string;
          created_at?: string;
          id?: string;
          kind?: Database["public"]["Enums"]["notification_kind"];
          post_id?: string | null;
          read_at?: string | null;
          recipient_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_recipient_id_fkey";
            columns: ["recipient_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      post_likes: {
        Row: {
          created_at: string;
          post_id: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          post_id: string;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          post_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "post_likes_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_likes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      post_media: {
        Row: {
          alt: string | null;
          bucket: string;
          byte_size: number | null;
          created_at: string;
          duration_ms: number | null;
          height: number | null;
          id: string;
          kind: Database["public"]["Enums"]["media_kind"];
          mime_type: string;
          owner_id: string;
          position: number;
          post_id: string;
          storage_path: string;
          width: number | null;
        };
        Insert: {
          alt?: string | null;
          bucket?: string;
          byte_size?: number | null;
          created_at?: string;
          duration_ms?: number | null;
          height?: number | null;
          id?: string;
          kind: Database["public"]["Enums"]["media_kind"];
          mime_type: string;
          owner_id?: string;
          position?: number;
          post_id: string;
          storage_path: string;
          width?: number | null;
        };
        Update: {
          alt?: string | null;
          bucket?: string;
          byte_size?: number | null;
          created_at?: string;
          duration_ms?: number | null;
          height?: number | null;
          id?: string;
          kind?: Database["public"]["Enums"]["media_kind"];
          mime_type?: string;
          owner_id?: string;
          position?: number;
          post_id?: string;
          storage_path?: string;
          width?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "post_media_owner_id_fkey";
            columns: ["owner_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "post_media_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
        ];
      };
      posts: {
        Row: {
          author_id: string;
          body: string;
          created_at: string;
          deleted_at: string | null;
          is_entry: boolean;
          id: string;
          like_count: number;
          parent_id: string | null;
          reply_count: number;
          repost_count: number;
          repost_of_id: string | null;
          root_id: string | null;
          updated_at: string;
          visibility: Database["public"]["Enums"]["post_visibility"];
          world_id: string | null;
        };
        Insert: {
          author_id?: string;
          body?: string;
          created_at?: string;
          deleted_at?: string | null;
          is_entry?: boolean;
          id?: string;
          like_count?: number;
          parent_id?: string | null;
          reply_count?: number;
          repost_count?: number;
          repost_of_id?: string | null;
          root_id?: string | null;
          updated_at?: string;
          visibility?: Database["public"]["Enums"]["post_visibility"];
          world_id?: string | null;
        };
        Update: {
          author_id?: string;
          body?: string;
          created_at?: string;
          deleted_at?: string | null;
          is_entry?: boolean;
          id?: string;
          like_count?: number;
          parent_id?: string | null;
          reply_count?: number;
          repost_count?: number;
          repost_of_id?: string | null;
          root_id?: string | null;
          updated_at?: string;
          visibility?: Database["public"]["Enums"]["post_visibility"];
          world_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "posts_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "posts_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "posts_repost_of_id_fkey";
            columns: ["repost_of_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "posts_world_id_fkey";
            columns: ["world_id"];
            isOneToOne: false;
            referencedRelation: "worlds";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "posts_root_id_fkey";
            columns: ["root_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
        ];
      };
      profile_verifications: {
        Row: {
          note: string;
          user_id: string;
          verification_type: string;
          verified_at: string;
          verified_by: string | null;
        };
        Insert: {
          note?: string;
          user_id: string;
          verification_type: string;
          verified_at?: string;
          verified_by?: string | null;
        };
        Update: {
          note?: string;
          user_id?: string;
          verification_type?: string;
          verified_at?: string;
          verified_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "profile_verifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profile_verifications_verified_by_fkey";
            columns: ["verified_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          bio: string;
          created_at: string;
          display_name: string;
          follower_count: number;
          following_count: number;
          id: string;
          post_count: number;
          updated_at: string;
          username: string;
        };
        Insert: {
          avatar_url?: string | null;
          bio?: string;
          created_at?: string;
          display_name: string;
          follower_count?: number;
          following_count?: number;
          id: string;
          post_count?: number;
          updated_at?: string;
          username: string;
        };
        Update: {
          avatar_url?: string | null;
          bio?: string;
          created_at?: string;
          display_name?: string;
          follower_count?: number;
          following_count?: number;
          id?: string;
          post_count?: number;
          updated_at?: string;
          username?: string;
        };
        Relationships: [];
      };
      support_ledger: {
        Row: {
          actor_id: string | null;
          created_at: string;
          credits: number;
          id: string;
          note: string | null;
          reason: string;
          reputation: number;
          request_id: string | null;
          user_id: string;
        };
        Insert: {
          actor_id?: string | null;
          created_at?: string;
          credits?: number;
          id?: string;
          note?: string | null;
          reason: string;
          reputation?: number;
          request_id?: string | null;
          user_id: string;
        };
        Update: {
          actor_id?: string | null;
          created_at?: string;
          credits?: number;
          id?: string;
          note?: string | null;
          reason?: string;
          reputation?: number;
          request_id?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "support_ledger_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ledger_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "support_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ledger_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      support_reports: {
        Row: {
          created_at: string;
          id: string;
          reason: string;
          reporter_id: string;
          request_id: string;
          resolved_at: string | null;
          resolved_by: string | null;
          status: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          reason: string;
          reporter_id: string;
          request_id: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          reason?: string;
          reporter_id?: string;
          request_id?: string;
          resolved_at?: string | null;
          resolved_by?: string | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "support_reports_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "support_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_reports_reporter_id_fkey";
            columns: ["reporter_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      support_requests: {
        Row: {
          ask: string;
          category: string;
          completed_at: string | null;
          created_at: string;
          creator_id: string;
          description: string;
          featured: boolean;
          id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: string;
          supporter_count: number;
          target: number;
          title: string;
          updated_at: string;
          url: string;
        };
        Insert: {
          ask: string;
          category: string;
          completed_at?: string | null;
          created_at?: string;
          creator_id: string;
          description: string;
          featured?: boolean;
          id?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: string;
          supporter_count?: number;
          target: number;
          title: string;
          updated_at?: string;
          url: string;
        };
        Update: {
          ask?: string;
          category?: string;
          completed_at?: string | null;
          created_at?: string;
          creator_id?: string;
          description?: string;
          featured?: boolean;
          id?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: string;
          supporter_count?: number;
          target?: number;
          title?: string;
          updated_at?: string;
          url?: string;
        };
        Relationships: [
          {
            foreignKeyName: "support_requests_creator_id_fkey";
            columns: ["creator_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_requests_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      support_settings: {
        Row: {
          default_target: number;
          feedback_credits: number;
          feedback_reputation: number;
          id: boolean;
          max_target: number;
          min_target: number;
          min_visit_seconds: number;
          moderation: boolean;
          quick_confirm_seconds: number;
          request_cost: number;
          starter_credits: number;
          support_credits: number;
          support_reputation: number;
          updated_at: string;
        };
        Insert: {
          default_target?: number;
          feedback_credits?: number;
          feedback_reputation?: number;
          id?: boolean;
          max_target?: number;
          min_target?: number;
          min_visit_seconds?: number;
          moderation?: boolean;
          quick_confirm_seconds?: number;
          request_cost?: number;
          starter_credits?: number;
          support_credits?: number;
          support_reputation?: number;
          updated_at?: string;
        };
        Update: {
          default_target?: number;
          feedback_credits?: number;
          feedback_reputation?: number;
          id?: boolean;
          max_target?: number;
          min_target?: number;
          min_visit_seconds?: number;
          moderation?: boolean;
          quick_confirm_seconds?: number;
          request_cost?: number;
          starter_credits?: number;
          support_credits?: number;
          support_reputation?: number;
          updated_at?: string;
        };
        Relationships: [

        ];
      };
      support_visits: {
        Row: {
          confirmed_at: string | null;
          feedback: string;
          feedback_at: string | null;
          opened_at: string;
          reaction: string | null;
          request_id: string;
          user_id: string;
        };
        Insert: {
          confirmed_at?: string | null;
          feedback?: string;
          feedback_at?: string | null;
          opened_at?: string;
          reaction?: string | null;
          request_id: string;
          user_id: string;
        };
        Update: {
          confirmed_at?: string | null;
          feedback?: string;
          feedback_at?: string | null;
          opened_at?: string;
          reaction?: string | null;
          request_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "support_visits_request_id_fkey";
            columns: ["request_id"];
            isOneToOne: false;
            referencedRelation: "support_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_visits_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      world_chat_messages: {
        Row: {
          author_id: string;
          body: string;
          created_at: string;
          id: string;
          world_id: string;
        };
        Insert: {
          author_id?: string;
          body: string;
          created_at?: string;
          id?: string;
          world_id: string;
        };
        Update: {
          author_id?: string;
          body?: string;
          created_at?: string;
          id?: string;
          world_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "world_chat_messages_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "world_chat_messages_world_id_fkey";
            columns: ["world_id"];
            isOneToOne: false;
            referencedRelation: "worlds";
            referencedColumns: ["id"];
          },
        ];
      };
      world_members: {
        Row: {
          joined_at: string;
          user_id: string;
          world_id: string;
        };
        Insert: {
          joined_at?: string;
          user_id?: string;
          world_id: string;
        };
        Update: {
          joined_at?: string;
          user_id?: string;
          world_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "world_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "world_members_world_id_fkey";
            columns: ["world_id"];
            isOneToOne: false;
            referencedRelation: "worlds";
            referencedColumns: ["id"];
          },
        ];
      };
      world_host_picks: {
        Row: {
          created_at: string;
          post_id: string;
          world_id: string;
        };
        Insert: {
          created_at?: string;
          post_id: string;
          world_id: string;
        };
        Update: {
          created_at?: string;
          post_id?: string;
          world_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "world_host_picks_post_id_fkey";
            columns: ["post_id"];
            isOneToOne: false;
            referencedRelation: "posts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "world_host_picks_world_id_fkey";
            columns: ["world_id"];
            isOneToOne: false;
            referencedRelation: "worlds";
            referencedColumns: ["id"];
          },
        ];
      };
      worlds: {
        Row: {
          competition: boolean;
          cover_url: string | null;
          created_at: string;
          created_by: string | null;
          description: string;
          ends_at: string;
          entries_close_at: string | null;
          entry_limit: number;
          id: string;
          participant_count: number;
          points_host_pick: number;
          points_reaction: number;
          points_reply: number;
          prize: string | null;
          slug: string;
          starts_at: string;
          tagline: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          competition?: boolean;
          cover_url?: string | null;
          created_at?: string;
          created_by?: string | null;
          description?: string;
          ends_at: string;
          entries_close_at?: string | null;
          entry_limit?: number;
          id?: string;
          participant_count?: number;
          points_host_pick?: number;
          points_reaction?: number;
          points_reply?: number;
          prize?: string | null;
          slug: string;
          starts_at: string;
          tagline?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          competition?: boolean;
          cover_url?: string | null;
          created_at?: string;
          created_by?: string | null;
          description?: string;
          ends_at?: string;
          entries_close_at?: string | null;
          entry_limit?: number;
          id?: string;
          participant_count?: number;
          points_host_pick?: number;
          points_reaction?: number;
          points_reply?: number;
          prize?: string | null;
          slug?: string;
          starts_at?: string;
          tagline?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "worlds_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      dm_open: { Args: { p_peer: string }; Returns: string };
      dm_send: { Args: { p_conversation: string; p_device: string; p_content: Json }; Returns: { id: string; created_at: string }[] };
      dm_mark_read: { Args: { p_conversation: string }; Returns: undefined };
      dm_mark_delivered: { Args: Record<PropertyKey, never>; Returns: undefined };
      dm_blocked_between: { Args: { a: string; b: string }; Returns: boolean };
      dm_inbox: {
        Args: Record<PropertyKey, never>;
        Returns: {
          conversation_id: string;
          peer_id: string;
          last_message_at: string;
          last_message_id: string | null;
          last_sender_id: string | null;
          last_sender_device: string | null;
          last_content: Json | null;
          unread_count: number;
          my_last_read_at: string;
          peer_last_read_at: string;
          peer_last_delivered_at: string;
          blocked_by_me: boolean;
          can_send: boolean;
        }[];
      };
      dm_block: { Args: { p_user: string }; Returns: undefined };
      dm_unblock: { Args: { p_user: string }; Returns: undefined };
      dm_report: { Args: { p_conversation: string; p_reason: string; p_note: string; p_evidence: Json }; Returns: string };
      admin_dm_reports: {
        Args: Record<PropertyKey, never>;
        Returns: {
          id: string;
          reporter_id: string;
          reporter_username: string;
          reported_id: string;
          reported_username: string;
          reason: string;
          note: string;
          evidence: Json;
          status: string;
          created_at: string;
          reviewed_by_username: string | null;
          reviewed_at: string | null;
        }[];
      };
      admin_dm_report_set_status: { Args: { p_report: string; p_status: string }; Returns: undefined };
      e2e_upload_keys: { Args: { p_device: string; p_device_keys: Json; p_one_time_keys: Json; p_fallback_keys: Json }; Returns: Json };
      e2e_query_keys: { Args: { p_users: string[] }; Returns: Json };
      e2e_claim_keys: { Args: { p_request: Json }; Returns: Json };
      e2e_key_counts: { Args: { p_device: string }; Returns: Json };
      e2e_send_to_device: { Args: { p_event_type: string; p_messages: Json }; Returns: undefined };
      e2e_ack_to_device: { Args: { p_device: string; p_up_to: number }; Returns: undefined };
      e2e_device_changes: { Args: { p_since: string }; Returns: { user_id: string; changed_at: string }[] };
      e2e_delete_device: { Args: { p_device: string }; Returns: undefined };
      admin_audit: { Args: { p_limit?: number }; Returns: { action: string; admin_id: string | null; avatar_url: string | null; created_at: string; display_name: string | null; id: string; summary: string; username: string | null }[] };
      admin_support_adjust_credits: { Args: { p_delta: number; p_note: string; p_user: string }; Returns: undefined };
      admin_support_find_user: { Args: { p_handle: string }; Returns: { active_requests: number; avatar_url: string | null; credits: number; display_name: string; helped: number; id: string; reputation: number; username: string }[] };
      admin_support_moderate: { Args: { p_action: string; p_note?: string; p_request: string }; Returns: undefined };
      admin_support_reports: { Args: { p_status?: string }; Returns: { created_at: string; id: string; reason: string; reporter_avatar_url: string | null; reporter_display_name: string; reporter_id: string; reporter_username: string; request_id: string; request_status: string; request_title: string; status: string }[] };
      admin_support_resolve_report: { Args: { p_outcome: string; p_report: string }; Returns: undefined };
      admin_support_supporters: { Args: { p_request: string }; Returns: { avatar_url: string | null; confirmed_at: string | null; display_name: string; opened_at: string; seconds: number | null; user_id: string; username: string }[] };
      admin_support_suspicious: { Args: never; Returns: { at: string; avatar_url: string | null; detail: string; display_name: string; kind: string; request_id: string | null; user_id: string; username: string }[] };
      admin_unverify_user: { Args: { p_note?: string; p_user: string }; Returns: undefined };
      admin_user_lookup: { Args: { p_handle: string }; Returns: { avatar_url: string | null; bio: string; display_name: string; id: string; note: string | null; username: string; verification_type: string | null; verified_at: string | null; verified_by_username: string | null }[] };
      admin_verified_users: { Args: never; Returns: { avatar_url: string | null; bio: string; display_name: string; id: string; note: string | null; username: string; verification_type: string | null; verified_at: string | null; verified_by_username: string | null }[] };
      admin_verify_user: { Args: { p_note?: string; p_type: string; p_user: string }; Returns: undefined };
      can_view_post: { Args: { p_post_id: string }; Returns: boolean };
      confirm_support: { Args: { p_request: string }; Returns: { credits: number; reputation: number }[] };
      create_post: {
        Args: {
          p_body: string;
          p_media?: Json;
          p_parent_id?: string;
          p_visibility?: Database["public"]["Enums"]["post_visibility"];
        };
        Returns: {
          author_id: string;
          body: string;
          created_at: string;
          deleted_at: string | null;
          is_entry: boolean;
          id: string;
          like_count: number;
          parent_id: string | null;
          reply_count: number;
          repost_count: number;
          repost_of_id: string | null;
          root_id: string | null;
          updated_at: string;
          visibility: Database["public"]["Enums"]["post_visibility"];
          world_id: string | null;
        };
        SetofOptions: {
          from: "*";
          to: "posts";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_support_request: { Args: { p_ask: string; p_category: string; p_description: string; p_target: number; p_title: string; p_url: string }; Returns: Database["public"]["Tables"]["support_requests"]["Row"] };
      delete_post: { Args: { p_post_id: string }; Returns: undefined };
      create_world_post: {
        Args: { p_body: string; p_entry?: boolean; p_media?: Json; p_world_id: string };
        Returns: Database["public"]["Tables"]["posts"]["Row"];
        SetofOptions: {
          from: "*";
          to: "posts";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      feed_posts: {
        Args: { p_before?: string; p_limit?: number; p_scope?: string };
        Returns: {
          author_id: string;
          body: string;
          created_at: string;
          deleted_at: string | null;
          is_entry: boolean;
          id: string;
          like_count: number;
          parent_id: string | null;
          reply_count: number;
          repost_count: number;
          repost_of_id: string | null;
          root_id: string | null;
          updated_at: string;
          visibility: Database["public"]["Enums"]["post_visibility"];
          world_id: string | null;
        }[];
        SetofOptions: {
          from: "*";
          to: "posts";
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      generate_username: { Args: { seed: string }; Returns: string };
      is_admin: { Args: never; Returns: boolean };
      leave_support_feedback: { Args: { p_reaction: string | null; p_request: string; p_text: string }; Returns: { credits: number; reputation: number }[] };
      legacy_find_unmigrated_user: {
        Args: { p_email: string };
        Returns: {
          firebase_uid: string;
          user_id: string;
        }[];
      };
      mark_notifications_read: { Args: { p_ids?: string[] }; Returns: number };
      open_support: { Args: { p_request: string }; Returns: undefined };
      report_support_request: { Args: { p_reason: string; p_request: string }; Returns: undefined };
      set_post_like: { Args: { p_liked: boolean; p_post_id: string }; Returns: undefined };
      suggested_profiles: {
        Args: { p_limit?: number };
        Returns: {
          avatar_url: string | null;
          bio: string;
          created_at: string;
          display_name: string;
          follower_count: number;
          following_count: number;
          id: string;
          post_count: number;
          updated_at: string;
          username: string;
        }[];
        SetofOptions: {
          from: "*";
          to: "profiles";
          isOneToOne: false;
          isSetofReturn: true;
        };
      };
      support_config: { Args: never; Returns: Database["public"]["Tables"]["support_settings"]["Row"] };
      support_discover: { Args: { p_category?: string | null; p_limit?: number; p_query?: string | null; p_section?: string }; Returns: Database["public"]["Tables"]["support_requests"]["Row"][]; SetofOptions: { from: "*"; to: "support_requests"; isOneToOne: false; isSetofReturn: true } };
      support_feedback: { Args: { p_request: string }; Returns: { avatar_url: string | null; display_name: string; feedback: string; feedback_at: string; reaction: string | null; user_id: string; username: string }[] };
      support_profile_stats: { Args: { p_profile: string }; Returns: { active_requests: number; helped: number; reputation: number }[] };
      support_wallet: { Args: never; Returns: { active_requests: number; credits: number; helped: number; reputation: number }[] };
      unread_notification_count: { Args: never; Returns: number };
      viewer_follows: { Args: { p_author: string }; Returns: boolean };
      world_leaderboard: {
        Args: { p_limit?: number; p_world_id: string };
        Returns: { entries: number; first_entry_at: string; points: number; rank: number; user_id: string }[];
      };
    };
    Enums: {
      media_kind: "image" | "video";
      notification_kind: "follow" | "like" | "reply" | "mention";
      post_visibility: "public" | "followers";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      media_kind: ["image", "video"],
      notification_kind: ["follow", "like", "reply", "mention"],
      post_visibility: ["public", "followers"],
    },
  },
} as const;
